version: "3"

services:

  server:
    image: scale-chat-server
    build:
      context: .
      dockerfile: src/server/Dockerfile
    ports:
      - "80:8080"
    environment:
      ENABLE_DIST: "true"
      DIST_SERVER: "redis:6379"
      DIST_TOPIC: "messages"
    deploy:
      replicas: 2
      resources:
          limits:
            cpus: "0.25"
            memory: 512M
          reservations:
            cpus: "0.25"
            memory: 256M
    depends_on:
      - redis
    labels:
      prometheus-job: "server"

  redis: 
    image: redis:6.2.6-alpine
    ports:
      - "6379:6379"

  prometheus:
    image: prom/prometheus:v2.31.1
    networks:
      - default
    depends_on:
      - cadvisor
    env_file:
      - .env
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - ./prometheus/data:/prometheus
      - /var/run/docker.sock:/var/run/docker.sock:ro

  grafana:
    image: grafana/grafana:8.2.5
    environment:
      PROMETHEUS_HOST: http://prometheus:9090
      # When deploying with docker stack deploy the .env file will be ignored and the default config will be initialized
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:ro

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    privileged: true
    depends_on:
      - server
