global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: golang
    metrics_path: /metrics
    static_configs:
      - targets:
          - server-one:8081
          - server-two:8081

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
