global:
  scrape_interval: 5s
  evaluation_interval: 5s

scrape_configs:
  - job_name: dockerswarm
    metrics_path: /metrics
    dockerswarm_sd_configs:
      - host: unix:///var/run/docker.sock
        role: tasks
    relabel_configs:
      # Only keep containers that should be running.
      - source_labels: [ __meta_dockerswarm_task_desired_state ]
        regex: running
        action: keep
      # Only keep containers that have a `prometheus-job` label.
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        regex: .+
        action: keep
      # Use the prometheus-job Swarm label as Prometheus job label.
      - source_labels: [ __meta_dockerswarm_service_label_prometheus_job ]
        target_label: job
      # Fetch metrics on port 8081.
      - source_labels: [ __address__ ]
        target_label: __address__
        replacement: $1:8081

  - job_name: cadvisor
    static_configs:
      - targets:
          - cadvisor:8080
